apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-git-source-cxwu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-git-source-cxwu
    app.kubernetes.io/part-of: build-suite-test-application-pzcz
  name: build-suite-test-component-git-source-cxwu
  namespace: appstudio-e2e-test
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-component-git-source-cxwu
status:
  loadBalancer: {}
